export const sidebar_mock = [
	{
		label: "Overview",
		route: "",
		section: null,
		icon: null,
		active: false,
		external: false,
	},
	{
		label: "Notebooks",
		route: "",
		section: null,
		icon: null,
		active: false,
		external: false,
	},
	{
		label: "Vercel Functions",
		route: "",
		section: "Compute",
		icon: null,
		active: false,
		external: false,
	},
	{
		label: "External APIs",
		route: "",
		section: "Compute",
		icon: null,
		active: false,
		external: false,
	},
	{
		label: "Middleware",
		route: "",
		section: "Compute",
		icon: null,
		active: false,
		external: false,
	},
	{
		label: "Edge Requests",
		route: "",
		section: "Edge Network",
		icon: null,
		active: false,
		external: false,
	},
	{
		label: "Fast Data Transfer",
		route: "",
		section: "Edge Network",
		icon: null,
		active: false,
		external: false,
	},
	{
		label: "Image Optimization",
		route: "",
		section: "Edge Network",
		icon: null,
		active: false,
		external: false,
	},
	{
		label: "Vercel Functions",
		route: "",
		section: "External",
		icon: null,
		active: false,
		external: true,
	},
	{
		label: "External APIs",
		route: "",
		section: "External",
		icon: null,
		active: false,
		external: true,
	},
]