GET http://localhost/api/finance/v1/currency
###
GET http://localhost/api/users/v1/users?limit=10&page=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMmFmYTUyLTIzMDUtNDM2Yy05NWYzLWFkN2Q3MGU4NmMzMCIsIm5pY2tuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluIiwibmFtZSI6ImFkbWluIiwibGFzdG5hbWUiOiJhZG1pbiIsImpvYl9wb3NpdGlvbiI6ImFkbWluIiwiZmtfcm9sZSI6MSwiaXNfYWRtaW4iOnRydWUsImlzX293bmVyIjp0cnVlLCJleHAiOjE3NjI0NjMyNjh9.JeQsxjSRiZK5uroYm6AtDXkNJak-T6pywYBiEioCleE